### ISSUE TITLE
Dialogue system 

### ISSUE THREAD

**Issue by hakanuca** [hakanuca/Pixel-Throne-Rise-of-the-King#1]
- [x] Create a Dialogue system for random or script based talking with npc & enemy.
- [x] Test the necessary features. (bugs,ranges and scripts)
- [x] Create a dialogue scripts variations.
![Screenshot from 2024-07-17 10-50-36](https://github.com/user-attachments/assets/a9c00872-2365-4d00-8e91-1fc944da54e3)

**Comment by YankUfuk** [comment]
1. yapay zekaya diyalog yazdırılacak
2. UI iyileştirilecek
3. daktilo efekti eklenecek
