### ISSUE TITLE
Some Small Bugfix

### ISSUE THREAD

**Issue by YankUfuk** [hakanuca/Pixel-Throne-Rise-of-the-King#103]
- [x] Final fight scene there is a fire it should not be on the level (Yanki)
- [x] Time counter must be optional(hakan)(off topic)
- [x] Final bosses projectile have some little issues about collider (yankı)
- [x] all bosses should have more health specially star boss (yanki)
- [x] flying normal enemies should be place better locations (atakan)

**Comment by hakanuca** [comment]
time counter should always be visible on the scene because of the competitive challenges effect.
