### ISSUE TITLE
Tutorial Scene New Features Updates

### ISSUE THREAD

**Issue by hakanuca** [hakanuca/Pixel-Throne-Rise-of-the-King#18]
- [x] Updates and expand the tutorial scenes missons
- [x] Updates the map for testing this new features test

**Additional:**
- [x] Test the Tutorial Scene

Optional:

- [x] Test this scene with person who is not in the team

**Comment by YankUfuk** [comment]
1. WASD Yürüme
2. E ile objelerle/npclerle etkileşim
3. K ile atak
4. L ile dodge
5. LEFT SHIFT ile hızlı koşma
6. Space ile zıplama 
7. Bufflar
