### ISSUE TITLE
Checkpoint System

### ISSUE THREAD

**Issue by YankUfuk** [hakanuca/Pixel-Throne-Rise-of-the-King#19]

**Comment by YankUfuk** [comment]
https://youtu.be/VE_bkPrrZdE?si=0bG09D3i_4rQlViB

**Comment by YusufAtakanUnal** [comment]
Checkpoint için uygun bir nesne bulunması gerek

**Comment by hakanuca** [comment]
All logic revised and completed. The scenes tested but it should be tested on general bug test.
