### ISSUE TITLE
Lightning Features

### ISSUE THREAD

**Issue by YankUfuk** [hakanuca/Pixel-Throne-Rise-of-the-King#20]

**Comment by YankUfuk** [comment]
Yeterince vakit kalırsa ışıklar geliştirilebilir ancak şu noktada fazla önemli sayılmaz

**Comment by hakanuca** [comment]
- [x] CAVE BIG
- [x] CAVE SMALL
- [x] FINAL FIGHT
- [x] FINAL MAP
- [x] INFINITY MAP
- [x] KINGDOM MAP 
- [x] KINGDOM 2
- [x] SKUL MAP

**Comment by hakanuca** [comment]
new lightning configurations added on game.
