### ISSUE TITLE
Map Playable Borders Check -MAP TEST 🚨 IMPORTANT 🚨 

### ISSUE THREAD

**Issue by hakanuca** [hakanuca/Pixel-Throne-Rise-of-the-King#27]
### Playable Map Testing Guidelines
**Map Boundaries**

-   Check the boundaries to ensure the ground layer allows the character to walk, run, and jump properly.
-   Note any issues where the character falls outside these limits, gets teleported, or gets stuck.

**Error Reporting**

- Document any errors, including instances of falling outside boundaries, teleportation issues, or getting stuck.
- Provide detailed notes and screenshots where necessary.

 **Trap Testing**

- Test all traps on the map to ensure they function correctly.
- Comment on any traps that do not work, including the location on the map and a screenshot of the issue.

**General Map Testing**

- Perform a comprehensive test of the entire map as a fully playable area to ensure all elements work as intended.

**Comment by hakanuca** [comment]
@YusufAtakanUnal @YankUfuk 

Report the bugs or problems here like that format: 

1. MAP NAME
2. PROBLEM
3. SPECIFIC REASON (optional)
4. SCREENSHOT

**Comment by YusufAtakanUnal** [comment]
1.Cave Scene
2.Enemies on the map functionally useless 
3.![cave-scene-1](https://github.com/user-attachments/assets/a3628cfd-424e-470e-bbe4-3bda9718d126)

**Comment by YusufAtakanUnal** [comment]
1.Cave Scene
2.Character cannot jump while on the platform
3.![cave-scene-2](https://github.com/user-attachments/assets/c7d547b4-5da5-490d-9ca9-8baee2899769)

**Comment by YusufAtakanUnal** [comment]
1.Onur Scenes
2.On both maps, the elevators are not visible and do not work correctly.
3.
![Ekran görüntüsü 2024-08-03 194123](https://github.com/user-attachments/assets/f2ab0c97-5729-48b5-a808-5e6c721e3b4f)
![onur-scene-2](https://github.com/user-attachments/assets/953a0102-56a8-48fa-b3f9-b8322ad0e13c)

**Comment by hakanuca** [comment]
> 1.Cave Scene 2.Enemies on the map functionally useless 3.![cave-scene-1](https://private-user-images.githubusercontent.com/160357551/354832489-a3628cfd-424e-470e-bbe4-3bda9718d126.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjQyNjYzMjcsIm5iZiI6MTcyNDI2NjAyNywicGF0aCI6Ii8xNjAzNTc1NTEvMzU0ODMyNDg5LWEzNjI4Y2ZkLTQyNGUtNDcwZS1iYmU0LTNiZGE5NzE4ZDEyNi5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQwODIxJTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MDgyMVQxODQ3MDdaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT02OTU0ZTA5YTNiZjZhMmUzZTZmN2NkMzEzYzgyNmQ3MTQ2ZDk2YjFmY2FmMzc1MGRiMzc0MGVkMTU5YjNjNjY0JlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.0eAChJJpSSvCZgTgdvM54Fu0p6ETf-ckdkE1tdagarQ)

@YankUfuk Can you add new enemy types on this part ? I think the patrolling pig enemy is so simple for this part.

**Comment by hakanuca** [comment]
> 1.Onur Scenes 2.On both maps, the elevators are not visible and do not work correctly. 3. ![Ekran görüntüsü 2024-08-03 194123](https://private-user-images.githubusercontent.com/160357551/354832625-f2ab0c97-5729-48b5-a808-5e6c721e3b4f.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjQyNjYzMjcsIm5iZiI6MTcyNDI2NjAyNywicGF0aCI6Ii8xNjAzNTc1NTEvMzU0ODMyNjI1LWYyYWIwYzk3LTU3MjktNDhiNS1hODA4LTVlNmM3MjFlM2I0Zi5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQwODIxJTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MDgyMVQxODQ3MDdaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT0wYjU1MmQ4MjRlNTJlNTdmYjg4ODI3Yzg2Njc5M2NkYzAwMGQxYWNlZGY0ZTVmMjM3ZDlkNjljY2I4YWZkZWExJlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.MZ5h2UxtofHMNXZkMsFy3lGV7UVuBsnZsWN_lLlxQd0) ![onur-scene-2](https://private-user-images.githubusercontent.com/160357551/354832636-953a0102-56a8-48fa-b3f9-b8322ad0e13c.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjQyNjYzMjcsIm5iZiI6MTcyNDI2NjAyNywicGF0aCI6Ii8xNjAzNTc1NTEvMzU0ODMyNjM2LTk1M2EwMTAyLTU2YTgtNDhmYS1iM2Y5LWI4MzIyYWQwZTEzYy5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQwODIxJTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MDgyMVQxODQ3MDdaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT0wNDNkOTg3MTkwNTMwZjI4MjBiZGU1ZTc4OWY3Y2YyNWU5YjFkYmY1ZDIwOTFhYjk3NzIwODcyYmM1NDdjMGMzJlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.sgIWLjVG1tUB-dfr6I5oWXehb4ItkM0zQXfOZsU5CJg)

@YusufAtakanUnal this error fixed

**Comment by hakanuca** [comment]
> 1.Cave Scene 2.Character cannot jump while on the platform 3.![cave-scene-2](https://private-user-images.githubusercontent.com/160357551/354832568-c7d547b4-5da5-490d-9ca9-8baee2899769.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjQyNjYzMjcsIm5iZiI6MTcyNDI2NjAyNywicGF0aCI6Ii8xNjAzNTc1NTEvMzU0ODMyNTY4LWM3ZDU0N2I0LTVkYTUtNDkwZC05Y2E5LThiYWVlMjg5OTc2OS5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQwODIxJTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MDgyMVQxODQ3MDdaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT05YzU2NTg3MzMyMzMyOWMxMzgxNTU3YmFmN2JhM2YwYTUxM2IzODljYTUwMjgyYmMyZjFhYWQ4ZjkxNDk4NDAyJlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.7zsdR4fvuymj4eaYMAUahX9L1COIKJlDJT6hZ2ky8yU)

@YusufAtakanUnal this bug fixed
