### ISSUE TITLE
🚨 GENERAL TEST FOR EVERY TOPIC 🚨 

### ISSUE THREAD

**Issue by hakanuca** [hakanuca/Pixel-Throne-Rise-of-the-King#44]
### TEST FOR SOUNDS

- [x] Check sounds for every map.

**Check SFX for** 
- [x] ATTACK 
- [x] FIRE
- [ ] LAVA
- [x] RUNNING
- [x] CANON

### TEST FOR COLLECTIBLE KEY LOGIC

- [x] Check the collectible keys.

### TEST FOR COLLECTIBLE HEALTH BUFF

- [x] Check the collectible health buff.

### TEST FOR CANON GUN

- [x] Check the canon guns with damage.

### TEST FOR ENEMIES

- [x] Check the enemies. They should work with no bug and They can be interactive.

**Comment by hakanuca** [comment]
@YusufAtakanUnal This is the general test issue for playtests

**Comment by YusufAtakanUnal** [comment]
FOR SFX
-There is no sound from lava on most maps(except Cave Big Map)

**Comment by YusufAtakanUnal** [comment]
FOR COLLECTIBLE KEY LOGIC
-Does not work on any maps
![Ekran görüntüsü 2024-09-11 135432](https://github.com/user-attachments/assets/720efeae-b608-45e8-94fa-376b41da70f1)

**Comment by YusufAtakanUnal** [comment]
FOR CHARACTER
-When the character dies, the game does not restart and the character's corpse can both fly and drag.
-The character can survive even though he doesn't have 3 lives.
-The character can jump when touching the ceiling
![Ekran görüntüsü 2024-09-11 135753](https://github.com/user-attachments/assets/46d0a0f3-3432-4175-9059-dddf4f7772a5)

**Comment by YusufAtakanUnal** [comment]
FOR ANIMATIONS
-When we make too many dashes, the animation of the dash gets distorted.

**Comment by YusufAtakanUnal** [comment]
FOR MAPS
-You can't jump in Kingdom Short Map 
![Ekran görüntüsü 2024-09-11 150636](https://github.com/user-attachments/assets/1541a3ad-afa7-4ff4-b80b-54b6083a7c4c)

**Comment by YusufAtakanUnal** [comment]
FOR OBJECTS
-Jumpads are not working
![Ekran görüntüsü 2024-09-11 144213](https://github.com/user-attachments/assets/c8f10279-8251-4b20-a51a-d5d5059aa616)

**Comment by hakanuca** [comment]
All errors fixed.
