### ISSUE TITLE
Door Feature Should be Checked for Every Map

### ISSUE THREAD

**Issue by hakanuca** [hakanuca/Pixel-Throne-Rise-of-the-King#71]

**Comment by YusufAtakanUnal** [comment]
cave map - kapısı 10 anahtar toplamadan açılıyor 

infinity map - 1) kapıdan girilmiyor 
               2)checkpointe girdiğin zaman önceki anahtar sayın ne olursa olsun anahtarın 6 oluyor

kingdom map - kapıdan girilmiyor

final map - kapıdan girilmiyor

skull map - 1)bossu kesince kapı kayboluyor
            2)müzik tekrar ederken kesildiği kısım çok batıyor

**Comment by hakanuca** [comment]
cave map 10 anahtar roplamadan acilma sorunu duzeltildi

**Comment by hakanuca** [comment]
infinity map kapi sorunu duzeltildi
6 anahtar baslama sorunu know issue designda boyle olmasina karar verildi duzeltilmiycek

**Comment by hakanuca** [comment]
kingdom kapi duzeltildi

**Comment by hakanuca** [comment]
final map duzeltildi

**Comment by hakanuca** [comment]
skull duzeltildi
