### ISSUE TITLE
Test The Tutorial Scene

### ISSUE THREAD

**Issue by hakanuca** [hakanuca/Pixel-Throne-Rise-of-the-King#87]
Tutorial scenedeki tum elementleri test et.
kapi mekanigi 
anahtar mekanigi
can mekanigi
dusmanlar
engeller
vb.
tum herseyi test et bulunan hata ve sikintilari bu issue altina raporla. tesekkurler

**Comment by YusufAtakanUnal** [comment]
hasar yemeden geçmek imkansız
![ateşler](https://github.com/user-attachments/assets/b09538d3-287a-4bd3-8543-7201b049b5bc)

**Comment by YusufAtakanUnal** [comment]
enemy uçuyomuş gibi gözüküyor
![uçuyo](https://github.com/user-attachments/assets/69115209-560f-4cb4-86fc-f306a87e6141)

**Comment by hakanuca** [comment]
all of them fixed
